using Aurora.Flowboard.Domain.Components;
using Aurora.Flowboard.Domain.FlowStateTemplates;
using Aurora.Flowboard.Domain.Milestones;
using Aurora.Flowboard.Domain.Projects;
using Aurora.Flowboard.Domain.Users;
using Aurora.Flowboard.Domain.WorkItems;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;

namespace Aurora.Flowboard.Infrastructure.Database;

public sealed class ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
    : DbContext(options), IApplicationDbContext
{
    internal const string DefaultSchema = "flowboard";

    public DbSet<User> Users { get; set; } = null!;
    public DbSet<UserToken> UserTokens { get; set; } = null!;
    public DbSet<Project> Projects { get; set; } = null!;
    public DbSet<ProjectMember> ProjectMembers { get; set; } = null!;
    public DbSet<ProjectChangeLog> ProjectChangeLogs { get; set; } = null!;
    public DbSet<Component> Components { get; set; } = null!;
    public DbSet<Milestone> Milestones { get; set; } = null!;
    public DbSet<FlowState> FlowStates { get; set; } = null!;
    public DbSet<FlowTransition> FlowTransitions { get; set; } = null!;
    public DbSet<FlowStateTemplate> FlowStateTemplates { get; set; } = null!;
    public DbSet<TemplateFlowState> TemplateFlowStates { get; set; } = null!;
    public DbSet<WorkItem> WorkItems { get; set; } = null!;
    public DbSet<WorkItemTag> WorkItemTags { get; set; } = null!;
    public DbSet<Comment> Comments { get; set; } = null!;
    public DbSet<TimeEntry> TimeEntries { get; set; } = null!;
    public DbSet<WorkItemChangeLog> WorkItemChangeLogs { get; set; } = null!;
    public DbSet<StateTransitionHistory> StateTransitionHistories { get; set; } = null!;

    public Task<IDbContextTransaction> BeginTransactionAsync(CancellationToken cancellationToken = default) =>
        Database.BeginTransactionAsync(cancellationToken);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema(DefaultSchema);
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(ApplicationDbContext).Assembly);

        // Guid keys are generated by the domain (BaseEntity / entity factories), never by the
        // store. Without this, EF's convention treats them as ValueGeneratedOnAdd and infers a
        // non-default key means the row already exists — so a new child added to a tracked
        // aggregate is tracked as Modified instead of Added, causing a DbUpdateConcurrencyException.
        foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())
        {
            IMutableKey? primaryKey = entityType.FindPrimaryKey();

            foreach (IMutableProperty keyProperty in primaryKey?.Properties ?? [])
            {
                if (keyProperty.ClrType == typeof(Guid))
                {
                    keyProperty.ValueGenerated = ValueGenerated.Never;
                }
            }
        }

        base.OnModelCreating(modelBuilder);
    }
}
