// <auto-generated />
using System;
using Aurora.Flowboard.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aurora.Flowboard.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817201620_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flowboard")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurora.Flowboard.Domain.Components.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_components_created_by");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_components_project_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_components_project_id_name");

                    b.ToTable("components", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.FlowStateTemplates.FlowStateTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_flow_state_templates");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_flow_state_templates_created_by");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_flow_state_templates_kind");

                    b.ToTable("flow_state_templates", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.FlowStateTemplates.TemplateFlowState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("FlowStateTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_state_template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_template_flow_states");

                    b.HasIndex("FlowStateTemplateId")
                        .HasDatabaseName("ix_template_flow_states_flow_state_template_id");

                    b.ToTable("template_flow_states", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Milestones.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetEndDate")
                        .HasColumnType("date")
                        .HasColumnName("target_end_date");

                    b.Property<DateOnly?>("TargetStartDate")
                        .HasColumnType("date")
                        .HasColumnName("target_start_date");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_milestones");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_milestones_created_by");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_milestones_project_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_milestones_project_id_name");

                    b.ToTable("milestones", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.FlowState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_flow_states");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_flow_states_project_id");

                    b.ToTable("flow_states", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.FlowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_state_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ToStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_state_id");

                    b.PrimitiveCollection<int[]>("_allowedRoles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("allowed_roles");

                    b.HasKey("Id")
                        .HasName("pk_flow_transitions");

                    b.HasIndex("FromStateId")
                        .HasDatabaseName("ix_flow_transitions_from_state_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_flow_transitions_project_id");

                    b.HasIndex("ToStateId")
                        .HasDatabaseName("ix_flow_transitions_to_state_id");

                    b.HasIndex("ProjectId", "FromStateId", "ToStateId")
                        .IsUnique()
                        .HasDatabaseName("ix_flow_transitions_project_id_from_state_id_to_state_id");

                    b.ToTable("flow_transitions", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("WorkItemCounter")
                        .HasColumnType("integer")
                        .HasColumnName("work_item_counter");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_projects_created_by");

                    b.ToTable("projects", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.ProjectChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffectedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_entity_id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_type");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<DateTime>("ChangedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_on_utc");

                    b.Property<string>("NewKind")
                        .HasColumnType("text")
                        .HasColumnName("new_kind");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_project_change_logs");

                    b.HasIndex("ChangedById")
                        .HasDatabaseName("ix_project_change_logs_changed_by_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_change_logs_project_id");

                    b.ToTable("project_change_logs", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_on_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_members_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_members_project_id_user_id");

                    b.ToTable("project_members", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Users.UserToken", b =>
                {
                    b.Property<Guid>("UserTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_token_id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("AccessTokenExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_on_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("IssuedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_on_utc");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_on_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UserTokenId")
                        .HasName("pk_user_tokens");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tokens_refresh_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tokens_user_id");

                    b.ToTable("user_tokens", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_comments");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_comments_work_item_id");

                    b.ToTable("work_item_comments", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.StateTransitionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<DateTime>("ChangedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_on_utc");

                    b.Property<Guid?>("FromStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_state_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ToStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_state_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_state_transition_histories");

                    b.HasIndex("FromStateId")
                        .HasDatabaseName("ix_work_item_state_transition_histories_from_state_id");

                    b.HasIndex("ToStateId")
                        .HasDatabaseName("ix_work_item_state_transition_histories_to_state_id");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_state_transition_histories_work_item_id");

                    b.ToTable("work_item_state_transition_histories", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("Hours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("hours");

                    b.Property<DateTime>("LoggedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_on_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_time_entries");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_time_entries_work_item_id");

                    b.ToTable("work_item_time_entries", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on_utc");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EstimatedCompletionDate")
                        .HasColumnType("date")
                        .HasColumnName("estimated_completion_date");

                    b.Property<int?>("EstimatedPoints")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_points");

                    b.Property<Guid>("FlowStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("flow_state_id");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_work_items_code");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_work_items_component_id");

                    b.HasIndex("FlowStateId")
                        .HasDatabaseName("ix_work_items_flow_state_id");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("ix_work_items_milestone_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_work_items_project_id");

                    b.ToTable("work_items", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItemChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffectedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_entity_id");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("change_type");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<DateTime>("ChangedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_on_utc");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_change_logs");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_work_item_change_logs_work_item_id");

                    b.ToTable("work_item_change_logs", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItemTag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id")
                        .HasName("pk_work_item_tags");

                    b.HasIndex("WorkItemId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_work_item_tags_work_item_id_name");

                    b.ToTable("work_item_tags", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_processed");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "flowboard");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Components.Component", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_components_users_created_by");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_components_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.FlowStateTemplates.FlowStateTemplate", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flow_state_templates_users_created_by");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.FlowStateTemplates.TemplateFlowState", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.FlowStateTemplates.FlowStateTemplate", null)
                        .WithMany("States")
                        .HasForeignKey("FlowStateTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_flow_states_flow_state_templates_flow_state_templa");

                    b.OwnsOne("Aurora.Flowboard.Domain.Shared.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("TemplateFlowStateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("color");

                            b1.HasKey("TemplateFlowStateId");

                            b1.ToTable("template_flow_states", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("TemplateFlowStateId")
                                .HasConstraintName("fk_template_flow_states_template_flow_states_id");
                        });

                    b.Navigation("Color")
                        .IsRequired();
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Milestones.Milestone", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_users_created_by");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_milestones_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.FlowState", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", null)
                        .WithMany("FlowStates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flow_states_projects_project_id");

                    b.OwnsOne("Aurora.Flowboard.Domain.Shared.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("FlowStateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("color");

                            b1.HasKey("FlowStateId");

                            b1.ToTable("flow_states", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("FlowStateId")
                                .HasConstraintName("fk_flow_states_flow_states_id");
                        });

                    b.Navigation("Color")
                        .IsRequired();
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.FlowTransition", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Projects.FlowState", null)
                        .WithMany()
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flow_transitions_flow_states_from_state_id");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", null)
                        .WithMany("FlowTransitions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flow_transitions_projects_project_id");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.FlowState", null)
                        .WithMany()
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flow_transitions_flow_states_to_state_id");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.Project", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Users.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_created_by");

                    b.OwnsOne("Aurora.Flowboard.Domain.Shared.Color", "Color", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("color");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.OwnsOne("Aurora.Flowboard.Domain.Projects.ProjectCode", "Prefix", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("prefix");

                            b1.HasKey("ProjectId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_projects_prefix");

                            b1.ToTable("projects", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_projects_projects_id");
                        });

                    b.Navigation("Color")
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Prefix")
                        .IsRequired();
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.ProjectChangeLog", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Users.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_change_logs_users_changed_by_id");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", null)
                        .WithMany("ChangeLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_change_logs_projects_project_id");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.ProjectMember", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", null)
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("Aurora.Flowboard.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Users.User", b =>
                {
                    b.OwnsOne("Aurora.Flowboard.Domain.Shared.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email");

                            b1.ToTable("users", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Aurora.Flowboard.Domain.Users.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsMany("Aurora.Flowboard.Domain.Users.Role", "Roles", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.HasKey("UserId", "Name")
                                .HasName("pk_user_roles");

                            b1.ToTable("user_roles", "flowboard");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_roles_users_user_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Users.UserToken", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Users.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.Comment", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.WorkItems.WorkItem", null)
                        .WithMany("Comments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_comments_work_items_work_item_id");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.StateTransitionHistory", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Projects.FlowState", null)
                        .WithMany()
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_item_state_transition_histories_flow_states_from_state");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.FlowState", null)
                        .WithMany()
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_state_transition_histories_flow_states_to_state_id");

                    b.HasOne("Aurora.Flowboard.Domain.WorkItems.WorkItem", null)
                        .WithMany("StateHistory")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_state_transition_histories_work_items_work_item_id");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.TimeEntry", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.WorkItems.WorkItem", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_time_entries_work_items_work_item_id");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItem", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.Components.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_items_components_component_id");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.FlowState", "FlowState")
                        .WithMany()
                        .HasForeignKey("FlowStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_flow_states_flow_state_id");

                    b.HasOne("Aurora.Flowboard.Domain.Milestones.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_items_milestones_milestone_id");

                    b.HasOne("Aurora.Flowboard.Domain.Projects.Project", "Project")
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_projects_project_id");

                    b.Navigation("Component");

                    b.Navigation("FlowState");

                    b.Navigation("Milestone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItemChangeLog", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.WorkItems.WorkItem", null)
                        .WithMany("ChangeLogs")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_change_logs_work_items_work_item_id");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItemTag", b =>
                {
                    b.HasOne("Aurora.Flowboard.Domain.WorkItems.WorkItem", null)
                        .WithMany("Tags")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_tags_work_items_work_item_id");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.FlowStateTemplates.FlowStateTemplate", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Projects.Project", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Components");

                    b.Navigation("FlowStates");

                    b.Navigation("FlowTransitions");

                    b.Navigation("Members");

                    b.Navigation("Milestones");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.Users.User", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Aurora.Flowboard.Domain.WorkItems.WorkItem", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Comments");

                    b.Navigation("StateHistory");

                    b.Navigation("Tags");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
